import { useState, useRef, useEffect } from "react";
import {
  Send,
  Loader2,
  Sparkles,
  User,
  Bot,
  Wrench,
  CheckCircle2,
  XCircle,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Card } from "@/components/ui/card";
import { useChat } from "@/contexts/ChatContext";
import { ApiService } from "@/services/api";
import type { Message, ToolCall } from "@/types";
import { cn } from "@/lib/utils";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeHighlight from "rehype-highlight";
import "highlight.js/styles/github.css";

export function ChatPanel() {
  const { currentSession, addMessage, updateLastMessage, setCurrentSessionId } =
    useChat();
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [toolCalls, setToolCalls] = useState<ToolCall[]>([]);
  const toolCallsRef = useRef<ToolCall[]>([]);
  const scrollRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [currentSession?.messages]);

  // Focus textarea on session change
  useEffect(() => {
    textareaRef.current?.focus();
  }, [currentSession?.id]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading || !currentSession) return;

    const userMessage: Message = {
      id: crypto.randomUUID(),
      role: "user",
      content: input.trim(),
      timestamp: Date.now(),
    };

    addMessage(userMessage);
    setInput("");
    setIsLoading(true);
    setToolCalls([]);
    toolCallsRef.current = []; // Clear previous tool calls

    // Create assistant message placeholder
    const assistantMessage: Message = {
      id: crypto.randomUUID(),
      role: "assistant",
      content: "",
      timestamp: Date.now(),
    };
    addMessage(assistantMessage);

    // Prepare messages for API - only send the last user message
    // The API maintains conversation history via sessionId
    const apiMessages = [
      {
        role: userMessage.role,
        content: userMessage.content,
      },
    ];

    try {
      // Determine session ID for API call
      // For new sessions (generated by frontend), send null to let backend create one
      const backendSessionId =
        currentSession.messages.length === 0 ? null : currentSession.id;

      // Use streaming API
      await ApiService.sendMessageStream(
        backendSessionId,
        apiMessages,
        // onChunk
        (content) => {
          updateLastMessage(content);
        },
        // onToolEvent
        (event) => {
          console.log("[ChatPanel] Tool event:", event);
          setToolCalls((prev) => {
            const existing = prev.find((t) => t.id === event.tool_call_id);

            let updated: ToolCall[];

            if (event.event === "tool:start") {
              if (existing) {
                updated = prev;
              } else {
                updated = [
                  ...prev,
                  {
                    id: event.tool_call_id,
                    name: event.tool_name,
                    state: "running",
                    startTime: event.timestamp,
                  },
                ];
              }
            } else if (event.event === "tool:end") {
              // Check if the tool execution failed
              const isFailed = (event as any).state === "Failed";
              const errorMsg = event.error || (event as any).error_message;
              updated = prev.map((t) =>
                t.id === event.tool_call_id
                  ? {
                      ...t,
                      state: isFailed ? "error" : "completed",
                      endTime: event.timestamp,
                      duration: event.duration_ms,
                      error: isFailed ? errorMsg : undefined,
                    }
                  : t,
              );
            } else if (event.event === "tool:error") {
              updated = prev.map((t) =>
                t.id === event.tool_call_id
                  ? {
                      ...t,
                      state: "error",
                      endTime: event.timestamp,
                      duration: event.duration_ms,
                      error: event.error,
                    }
                  : t,
              );
            } else {
              updated = prev;
            }

            toolCallsRef.current = updated;
            console.log("[ChatPanel] Updated toolCallsRef:", updated);
            return updated;
          });
        },
        // onComplete
        (sessionId) => {
          if (sessionId && sessionId !== currentSession.id) {
            // Update session with backend-generated ID
            setCurrentSessionId(sessionId);
          }
          // Save tool calls to the last message (use ref to get latest value)
          const finalToolCalls = toolCallsRef.current;
          if (finalToolCalls.length > 0) {
            console.log(
              "[ChatPanel] Saving tool calls to message:",
              finalToolCalls,
            );
            updateLastMessage("", finalToolCalls);
          }
          setIsLoading(false);
          setToolCalls([]);
          toolCallsRef.current = [];
        },
        // onError
        (error) => {
          console.error("Error sending message:", error);
          // Save tool calls even on error
          const finalToolCalls = toolCallsRef.current;
          if (finalToolCalls.length > 0) {
            console.log(
              "[ChatPanel] Saving tool calls on error:",
              finalToolCalls,
            );
            updateLastMessage(`\n\n[Error: ${error.message}]`, finalToolCalls);
          } else {
            updateLastMessage(`\n\n[Error: ${error.message}]`);
          }
          setIsLoading(false);
          setToolCalls([]);
          toolCallsRef.current = [];
        },
      );
    } catch (error) {
      console.error("Error sending message:", error);
      setIsLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit(e);
    }
  };

  if (!currentSession) {
    return (
      <div className="flex h-full items-center justify-center bg-background">
        <div className="text-center max-w-md">
          <div className="mb-6 inline-flex items-center justify-center w-20 h-20 rounded-2xl bg-primary shadow-lg">
            <Sparkles className="w-10 h-10 text-primary-foreground" />
          </div>
          <h3 className="text-2xl font-semibold text-primary mb-3">
            Welcome to Kode Agent Chat
          </h3>
          <p className="text-sm text-muted-foreground">
            Create a new chat to get started with your AI assistant
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-full flex-col bg-background">
      {/* Header */}
      <div className="border-b border-border p-4 bg-card shadow-sm">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-primary flex items-center justify-center shadow-lg">
            <Sparkles className="w-5 h-5 text-primary-foreground" />
          </div>
          <div>
            <h2 className="font-semibold text-primary">
              {currentSession.title}
            </h2>
            <p className="text-xs text-muted-foreground">
              {currentSession.messages.length} messages
            </p>
          </div>
        </div>
      </div>

      {/* Messages */}
      <ScrollArea className="flex-1 p-4 bg-background" ref={scrollRef}>
        <div className="space-y-4">
          {currentSession.messages.length === 0 ? (
            <div className="flex h-full items-center justify-center text-muted-foreground">
              <div className="text-center">
                <Bot className="w-12 h-12 mx-auto mb-3 opacity-50" />
                <p className="text-sm">Start a conversation...</p>
              </div>
            </div>
          ) : (
            currentSession.messages.map((message) => (
              <div
                key={message.id}
                className={cn(
                  "flex gap-3",
                  message.role === "user" ? "justify-end" : "justify-start",
                )}
              >
                {message.role === "assistant" && (
                  <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center shrink-0 shadow-md">
                    <Bot className="w-4 h-4 text-primary-foreground" />
                  </div>
                )}
                <Card
                  className={cn(
                    "p-4 shadow-sm",
                    message.role === "user"
                      ? "max-w-[70%] bg-primary text-primary-foreground rounded-2xl rounded-tr-sm"
                      : "flex-1 bg-card border border-border rounded-2xl rounded-tl-sm",
                  )}
                >
                  {/* Tool Calls Display */}
                  {message.role === "assistant" &&
                    message.toolCalls &&
                    message.toolCalls.length > 0 && (
                      <div className="mb-3">
                        <div className="flex items-center gap-2 text-xs font-semibold text-gray-700 dark:text-gray-200 mb-2">
                          <Wrench className="w-3 h-3" />
                          <span>Tool Calls</span>
                        </div>
                        <div className="space-y-1.5">
                          {message.toolCalls.map((tool) => (
                            <div
                              key={tool.id}
                              className={cn(
                                "flex items-center gap-2 text-xs p-2 rounded-lg border",
                                tool.state === "running" &&
                                  "bg-blue-50 dark:bg-blue-950/30 border-blue-200 dark:border-blue-800",
                                tool.state === "completed" &&
                                  "bg-green-50 dark:bg-green-950/30 border-green-200 dark:border-green-800",
                                tool.state === "error" &&
                                  "bg-red-50 dark:bg-red-950/30 border-red-200 dark:border-red-800",
                              )}
                            >
                              {tool.state === "running" && (
                                <Loader2 className="w-3 h-3 animate-spin text-blue-600 dark:text-blue-400" />
                              )}
                              {tool.state === "completed" && (
                                <CheckCircle2 className="w-3 h-3 text-green-600 dark:text-green-400" />
                              )}
                              {tool.state === "error" && (
                                <XCircle className="w-3 h-3 text-red-600 dark:text-red-400" />
                              )}
                              <span className="font-mono flex-1 truncate text-gray-900 dark:text-gray-100 font-semibold">
                                {tool.name}
                              </span>
                              {tool.state === "completed" && tool.duration && (
                                <span className="text-gray-900 dark:text-gray-100">
                                  {tool.duration}ms
                                </span>
                              )}
                              {tool.state === "error" && tool.error && (
                                <span
                                  className="text-red-600 dark:text-red-400 truncate max-w-[200px]"
                                  title={tool.error}
                                >
                                  {tool.error}
                                </span>
                              )}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  <div className="text-sm prose prose-sm dark:prose-invert max-w-none">
                    {message.role === "assistant" ? (
                      <ReactMarkdown
                        remarkPlugins={[remarkGfm]}
                        rehypePlugins={[rehypeHighlight]}
                        components={{
                          code: ({
                            node,
                            inline,
                            className,
                            children,
                            ...props
                          }: any) => {
                            return inline ? (
                              <code
                                className="px-1 py-0.5 rounded bg-muted text-foreground font-mono text-xs"
                                {...props}
                              >
                                {children}
                              </code>
                            ) : (
                              <code className={className} {...props}>
                                {children}
                              </code>
                            );
                          },
                          pre: ({ children, ...props }: any) => (
                            <pre
                              className="overflow-x-auto rounded-md bg-muted p-2 my-2 border border-border"
                              {...props}
                            >
                              {children}
                            </pre>
                          ),
                          p: ({ children, ...props }: any) => (
                            <p className="mb-2 last:mb-0" {...props}>
                              {children}
                            </p>
                          ),
                          ul: ({ children, ...props }: any) => (
                            <ul className="list-disc pl-4 mb-2" {...props}>
                              {children}
                            </ul>
                          ),
                          ol: ({ children, ...props }: any) => (
                            <ol className="list-decimal pl-4 mb-2" {...props}>
                              {children}
                            </ol>
                          ),
                          a: ({ children, ...props }: any) => (
                            <a
                              className="text-blue-600 dark:text-blue-400 underline hover:text-blue-800 dark:hover:text-blue-300"
                              {...props}
                            >
                              {children}
                            </a>
                          ),
                        }}
                      >
                        {message.content}
                      </ReactMarkdown>
                    ) : (
                      <div className="whitespace-pre-wrap break-words">
                        {message.content}
                      </div>
                    )}
                  </div>
                  <div
                    className={cn(
                      "mt-2 text-xs",
                      message.role === "user"
                        ? "text-primary-foreground/70"
                        : "text-muted-foreground",
                    )}
                  >
                    {new Date(message.timestamp).toLocaleTimeString()}
                  </div>
                </Card>
                {message.role === "user" && (
                  <div className="w-8 h-8 rounded-lg bg-accent flex items-center justify-center shrink-0 shadow-md">
                    <User className="w-4 h-4 text-primary" />
                  </div>
                )}
              </div>
            ))
          )}
          {isLoading && toolCalls.length > 0 && (
            <div className="flex flex-col gap-2 ml-11">
              <div className="text-xs text-gray-700 dark:text-gray-200 font-semibold mb-1">
                🔧 Tool Calls:
              </div>
              {toolCalls.map((tool) => (
                <Card
                  key={tool.id}
                  className={cn(
                    "p-3 shadow-sm border-l-4 transition-colors",
                    tool.state === "running" &&
                      "border-l-blue-500 bg-blue-50 dark:bg-blue-950/20",
                    tool.state === "completed" &&
                      "border-l-green-500 bg-green-50 dark:bg-green-950/20",
                    tool.state === "error" &&
                      "border-l-red-500 bg-red-50 dark:bg-red-950/20",
                  )}
                >
                  <div className="flex items-center gap-2 text-sm">
                    {tool.state === "running" && (
                      <Loader2 className="h-4 w-4 animate-spin text-blue-600 dark:text-blue-400" />
                    )}
                    {tool.state === "completed" && (
                      <CheckCircle2 className="h-4 w-4 text-green-600 dark:text-green-400" />
                    )}
                    {tool.state === "error" && (
                      <XCircle className="h-4 w-4 text-red-600 dark:text-red-400" />
                    )}
                    <Wrench className="h-3 w-3 text-gray-600 dark:text-gray-300" />
                    <span className="font-semibold text-gray-900 dark:text-gray-100">
                      {tool.name}
                    </span>
                    {tool.duration && (
                      <span className="text-xs text-gray-900 dark:text-gray-100 ml-auto">
                        {tool.duration}ms
                      </span>
                    )}
                  </div>
                  {tool.error && (
                    <div className="mt-1 text-xs text-red-600 dark:text-red-400">
                      Error: {tool.error}
                    </div>
                  )}
                </Card>
              ))}
            </div>
          )}
          {isLoading && (
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center shrink-0 shadow-md">
                <Bot className="w-4 h-4 text-primary-foreground" />
              </div>
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <Loader2 className="h-4 w-4 animate-spin" />
                <span>Thinking...</span>
              </div>
            </div>
          )}
        </div>
      </ScrollArea>

      {/* Input */}
      <div className="border-t border-border p-4 bg-card">
        <form onSubmit={handleSubmit} className="flex gap-3">
          <Textarea
            ref={textareaRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Type your message... (Shift+Enter for new line)"
            className="min-h-[60px] max-h-[200px] resize-none bg-background border-border"
            disabled={isLoading}
          />
          <Button
            type="submit"
            size="icon"
            disabled={!input.trim() || isLoading}
            className="h-[60px] w-[60px] shrink-0 rounded-xl shadow-lg"
          >
            {isLoading ? (
              <Loader2 className="h-5 w-5 animate-spin" />
            ) : (
              <Send className="h-5 w-5" />
            )}
          </Button>
        </form>
      </div>
    </div>
  );
}
